- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app

- name: Copy user service
  ansible.builtin.copy:
    src: user.service
    dest: /etc/systemd/system/user.service


- name: deamon realod and start
  ansible.builtin.systemd_service:
    daemon_reload: true


- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo


