- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs


- name: Copy catalogue service
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: mongo




