- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install mongodb client
  ansible.builtin.package:
    name: mongodb-org-shell
    state: present

- name: get the categories count
  ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: "{{component}}=='catalogue'"

- name: get the users count
  ansible.builtin.command:  mongo --host mongodb.daws76s.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: "{{component}}=='user'"


- name: load catalogue data
  ansible.builtin.command: mongo --host mongodb.daws76s.online < /app/schema/catalogue.js
  when: "{{component}}=='catalogue' and products_count.stdout == '0'"
 

- name: load user data
  ansible.builtin.command: mongo --host mongodb.daws76s.online < /app/schema/user.js
  when: "{{component}}=='user' and products_count.stdout == '0'"
  


- name: start and enable "{{component}}"
  ansible.builtin.service:
    name: "{{component}}"
    state: restarted
    enabled: yes